### ISSUE TITLE
Sharing iP code quality feedback [for @KohGuanZeh]

### ISSUE THREAD

**Issue by soc-se-script** [KohGuanZeh/ip#4]
@KohGuanZeh We did an automated analysis of your code to detect potential areas to improve the code quality. We are sharing the results below, to help you improve the iP code further.

IMPORTANT: Note that the script looked for **just a few easy-to-detect problems only**, and **at-most three example are given** i.e., there can be other areas/places to improve.

### Aspect: Tab Usage

No easy-to-detect issues :+1: 

### Aspect: Naming boolean variables/methods

No easy-to-detect issues :+1: 

### Aspect: Brace Style

No easy-to-detect issues :+1: 

### Aspect: Package Name Style

No easy-to-detect issues :+1: 

### Aspect: Class Name Style

No easy-to-detect issues :+1: 

### Aspect: Dead Code

No easy-to-detect issues :+1: 

### Aspect: Method Length

No easy-to-detect issues :+1: 

### Aspect: Class size

No easy-to-detect issues :+1: 

### Aspect: Header Comments

Example from [`src/main/java/duke/ui/MainWindow.java` lines `84-91`](https://github.com/KohGuanZeh/ip/blob/23be48e527d05e1467dca2ec47b870acf290abc2/src/main/java/duke/ui/MainWindow.java#L84..L91):

```java

    /**
     * For closing program by using the bye command.
     * Sleeps for specified milliseconds before closing the stage.
     * During this time, userInput and sendButton will be disabled.
     * If InterruptException is thrown, window closes immediately after printing error.
     *
     * @param millisDelay Delay before closing in milliseconds.
     */

``` 

**Suggestion:** Ensure method/class header comments follow the format specified in the coding standard, in particular, the phrasing of the overview statement.

### Aspect: Recent Git Commit Message

No easy-to-detect issues :+1: 

### Aspect: Binary files in repo

No easy-to-detect issues :+1: 

----

:information_source: The bot account used to post this issue is un-manned. **Do not reply to this post** (as those replies will not be read). Instead, contact `cs2103@comp.nus.edu.sg` if you want to follow up on this post.

**Comment by KohGuanZeh** [comment]
Fixed header comments. Thanks.
Commit: 80fe776f533afa034250d0989aef7d14323ffbf4
